apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared
data:
  config.yaml: |
    tunnel: kuby
    credentials-file: /etc/cloudflared/creds/credentials.json
    metrics: 0.0.0.0:2000
    no-autoupdate: true
    ingress:
    - hostname: "*.bolacha.dev"
      service: https://traefik.kube-system.svc.cluster.local:80
      originRequest:
        noTLSVerify: true
    - service: http_status:404
