apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: traefik
  source:
    repoURL: https://helm.traefik.io/traefik
    chart: traefik
    targetRevision: "37.0.0"
    helm:
      values: |
        ingressClass:
          enabled: true
          isDefaultClass: true
        service:
          type: LoadBalancer
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
