apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: argocd
  namespace: traefik
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`argocd.bolacha.dev`)
      kind: Rule
      services:
        - name: argocd-server
          port: 80
