apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
spec:
  destination:
    namespace: traefik
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://helm.traefik.io/traefik
    chart: traefik
    targetRevision: 27.0.0
    helm:
      values: |
        service:
          type: NodePort
        ingressClass:
          enabled: true
          isDefaultClass: true
        logs:
          general:
            level: INFO
          access:
            enabled: true
        metrics:
          prometheus:
            enabled: true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
