# Configure Network Ports and EntryPoints
# EntryPoints are the network listeners for incoming traffic.
service:
  type: NodePort

ingressClass:
  enabled: true
  isDefaultClass: true

# Enable Observability
logs:
  general:
    level: INFO
  # This enables access logs, outputting them to Traefik's standard output by default. The [Access Logs Documentation](https://doc.traefik.io/traefik/observability/access-logs/) covers formatting, filtering, and output options.
  access:
    enabled: true

# Enables Prometheus for Metrics
metrics:
  prometheus:
    enabled: true