apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudflared-argocd-admin
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: cloudflared
    server: https://kubernetes.default.svc
  source:
    repoURL: https://helmcharts.gruntwork.io
    chart: k8s-service
    targetRevision: v0.2.12
    helm:
      values: |
        applicationName: cloudflared-argocd-admin
        replicaCount: 1
        containerResources:
          requests:
            memory: "1024Mi"
            cpu: "1"
          limits:
            memory: "1024Mi"
            cpu: "1"
        service:
          enabled: false
        ingress:
          enabled: false
        containerImage:
          repository: cloudflare/cloudflared
          tag: 2022.5.0
          pullPolicy: Always
        containerCommand:
          - "cloudflared"
          - "--no-autoupdate"
          - "tunnel"
          - "--config"
          - "/etc/cloudflared/config/config.yaml"
          - "run"
        configMaps:
          tunnelcert:
            as: volume
            subPath: cert.pem
            mountPath: /etc/cloudflared/cert.pem
          credentials:
            as: volume
            subPath: credentials.json
            mountPath: /etc/cloudflared/creds/credentials.json
          cloudflared:
            as: volume
            mountPath: /etc/cloudflared/config
            items:
              config.yaml:
                filePath: config.yaml
        customResources:
          enabled: true
          resources:
            cloudflared_configmap: |
              apiVersion: v1
              kind: ConfigMap
              metadata:
                name: cloudflared
                namespace: cloudflared
              data:
                config.yaml: |
                  tunnel: kuby
                  credentials-file: /etc/cloudflared/creds/credentials.json
                  metrics: 0.0.0.0:2000
                  no-autoupdate: true
                  ingress:
                    - hostname: argocd.bolacha.dev
                      service: http://argocd-server.argocd.svc.cluster.local:80
                    - service: http_status:404
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true